package oracle.obiee.admin.ws;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://msk-02-orabits.tsretail.ru:9704/AdminService/AdminService?WSDL",
  targetNamespace="http://ws.admin.obiee.oracle/", name="AdminService")
public class AdminService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("oracle.obiee.admin.ws.AdminService");
      URL baseUrl = AdminService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            AdminService.class.getResource("http://msk-02-orabits.tsretail.ru:9704/AdminService/AdminService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://msk-02-orabits.tsretail.ru:9704/AdminService/AdminService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://msk-02-orabits.tsretail.ru:9704/AdminService/AdminService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://msk-02-orabits.tsretail.ru:9704/AdminService/AdminService?WSDL",
          e);
    }
  }

  public AdminService()
  {
    super(wsdlLocationURL,
          new QName("http://ws.admin.obiee.oracle/", "AdminService"));
  }

  public AdminService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="AdminPort")
  public oracle.obiee.admin.ws.Admin getAdminPort()
  {
    return (oracle.obiee.admin.ws.Admin) super.getPort(new QName("http://ws.admin.obiee.oracle/",
                                                                 "AdminPort"),
                                                       oracle.obiee.admin.ws.Admin.class);
  }

  @WebEndpoint(name="AdminPort")
  public oracle.obiee.admin.ws.Admin getAdminPort(WebServiceFeature... features)
  {
    return (oracle.obiee.admin.ws.Admin) super.getPort(new QName("http://ws.admin.obiee.oracle/",
                                                                 "AdminPort"),
                                                       oracle.obiee.admin.ws.Admin.class,
                                                       features);
  }
}
