package oracle.obiee.admin.ws;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://msk-02-orabits.tsretail.ru:9704/AdminService/AdminService?WSDL",
  targetNamespace="http://ws.admin.obiee.oracle/", name="Admin")
@XmlSeeAlso(
  { oracle.obiee.admin.ws.types.ObjectFactory.class, oracle.obiee.admin.ws.ObjectFactory.class })
public interface Admin
{
  @WebMethod
  @Action(input="", fault =
      { @FaultAction(value="http://ws.admin.obiee.oracle/Admin/callProcedure/Fault/ServerException",
          className=oracle.obiee.admin.ws.ServerException.class),
        @FaultAction(value="http://ws.admin.obiee.oracle/Admin/callProcedure/Fault/ValidationException",
          className=oracle.obiee.admin.ws.ValidationException.class) },
    output="")
  @ResponseWrapper(localName="callProcedureResponse", targetNamespace="http://ws.admin.obiee.oracle/",
    className="oracle.obiee.admin.ws.CallProcedureResponse")
  @RequestWrapper(localName="callProcedure", targetNamespace="http://ws.admin.obiee.oracle/",
    className="oracle.obiee.admin.ws.CallProcedure")
  public void callProcedure(@WebParam(targetNamespace="", name="procedureName")
    String procedureName, @WebParam(targetNamespace="", name="parameters",
      mode=Mode.INOUT)
    Holder<List<oracle.obiee.admin.ws.types.Parameter>> parameters)
    throws oracle.obiee.admin.ws.ServerException_Exception, oracle.obiee.admin.ws.ValidationException_Exception;

  @WebMethod
  @Action(input="", fault =
      { @FaultAction(value="http://ws.admin.obiee.oracle/Admin/callProcedureWithResults/Fault/ServerException",
          className=oracle.obiee.admin.ws.ServerException.class),
        @FaultAction(value="http://ws.admin.obiee.oracle/Admin/callProcedureWithResults/Fault/UnsupportedTypeException",
          className=oracle.obiee.admin.ws.UnsupportedTypeException.class),
        @FaultAction(value="http://ws.admin.obiee.oracle/Admin/callProcedureWithResults/Fault/ValidationException",
          className=oracle.obiee.admin.ws.ValidationException.class) },
    output="")
  @ResponseWrapper(localName="callProcedureWithResultsResponse",
    targetNamespace="http://ws.admin.obiee.oracle/", className="oracle.obiee.admin.ws.CallProcedureWithResultsResponse")
  @RequestWrapper(localName="callProcedureWithResults", targetNamespace="http://ws.admin.obiee.oracle/",
    className="oracle.obiee.admin.ws.CallProcedureWithResults")
  @WebResult(targetNamespace="")
  public oracle.obiee.admin.ws.types.Results callProcedureWithResults(@WebParam(targetNamespace="",
      name="procedureName")
    String procedureName, @WebParam(targetNamespace="", name="parameters",
      mode=Mode.INOUT)
    Holder<List<oracle.obiee.admin.ws.types.Parameter>> parameters)
    throws oracle.obiee.admin.ws.ServerException_Exception, oracle.obiee.admin.ws.UnsupportedTypeException_Exception, oracle.obiee.admin.ws.ValidationException_Exception;

  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="startExtenderResponse", targetNamespace="http://ws.admin.obiee.oracle/",
    className="oracle.obiee.admin.ws.StartExtenderResponse")
  @RequestWrapper(localName="startExtender", targetNamespace="http://ws.admin.obiee.oracle/",
    className="oracle.obiee.admin.ws.StartExtender")
  @WebResult(targetNamespace="")
  public String startExtender(@WebParam(targetNamespace="", name="adminBeanServerUrl")
    String adminBeanServerUrl, @WebParam(targetNamespace="", name="biAdminUser")
    String biAdminUser, @WebParam(targetNamespace="", name="biAdminPassword")
    String biAdminPassword, @WebParam(targetNamespace="", name="jobID")
    String jobID, @WebParam(targetNamespace="", name="connectionDetails")
    String connectionDetails);
}
