package oracle.bi.web.soap;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://msk-02-orabits.tsretail.ru:9704/analytics/saw.dll/wsdl/v6",
  targetNamespace="urn://oracle.bi.webservices/v6", name="MetadataService")
public class MetadataService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("oracle.bi.web.soap.MetadataService");
      URL baseUrl = MetadataService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            MetadataService.class.getResource("http://msk-02-orabits.tsretail.ru:9704/analytics/saw.dll/wsdl/v6");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://msk-02-orabits.tsretail.ru:9704/analytics/saw.dll/wsdl/v6");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://msk-02-orabits.tsretail.ru:9704/analytics/saw.dll/wsdl/v6");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://msk-02-orabits.tsretail.ru:9704/analytics/saw.dll/wsdl/v6",
          e);
    }
  }

  public MetadataService()
  {
    super(wsdlLocationURL,
          new QName("urn://oracle.bi.webservices/v6", "MetadataService"));
  }

  public MetadataService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="MetadataServiceSoap")
  public oracle.bi.web.soap.MetadataServiceSoap getMetadataServiceSoap()
  {
    return (oracle.bi.web.soap.MetadataServiceSoap) super.getPort(new QName("urn://oracle.bi.webservices/v6",
                                                                            "MetadataServiceSoap"),
                                                                  oracle.bi.web.soap.MetadataServiceSoap.class);
  }

  @WebEndpoint(name="MetadataServiceSoap")
  public oracle.bi.web.soap.MetadataServiceSoap getMetadataServiceSoap(WebServiceFeature... features)
  {
    return (oracle.bi.web.soap.MetadataServiceSoap) super.getPort(new QName("urn://oracle.bi.webservices/v6",
                                                                            "MetadataServiceSoap"),
                                                                  oracle.bi.web.soap.MetadataServiceSoap.class,
                                                                  features);
  }
}
